version: "3.8"

services:
  #######################################
  # Portfolio container
  #######################################
  portfolio:
    build:
      context: .
    container_name: portfolio
    ports:
      - "4040:3000"
    networks:
      - jannis
    restart: unless-stopped

networks:
  jannis:
    external: true